### ISSUE TITLE
Motion playback FPS issue after exporting bvh with provided code

### ISSUE THREAD

**Issue by haem-k** [orangeduck/lafan1-resolved#3]
Hi, thank you for sharing the resolved version of LAFAN1 dataset along with data processing codes!

I was running your `export_bvh.py` and found that the resulting motion in bvh is played faster than the original motion data. 
In my case, the cause was that my MotionBuilder Transport Controls was set to 30 FPS when recording the motion in bvh.
So I fixed this issue by adding a line setting 60 FPS for the control.

I thought this small fix might be helpful for others as well.
If you find it useful, I’d be happy to submit a pull request for your review.
If you have any other suggestions, please let me know. Thank you!

**Comment by orangeduck** [comment]
Thanks a lot! Yes please go ahead and open a pull request that sounds like a useful fix.

**Comment by haem-k** [comment]
Just sent pull request! Thank you
